# -*- coding: utf-8 -*-
"""Text/Img.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZJEFJPRs9VlFZOuS8BHhO1pNkz73wi0g
"""

!pip install diffusers transformers accelerate torch

import torch
from diffusers import StableDiffusionPipeline
import warnings

# Suppress the specific warning about tokenization spaces
warnings.filterwarnings("ignore", category=FutureWarning)

# Load the Stable Diffusion model and pipeline
model_id = "CompVis/stable-diffusion-v1-4"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")

# Save the model locally
pipe.save_pretrained("saved_model")

print("Model saved successfully!")

# Function to generate an image from text
def text_to_image(prompt, image_path="output_image.png"):
    # Generate the image
    with torch.autocast("cuda"):
        image = pipe(prompt, clean_up_tokenization_spaces=False).images[0]

    # Save the image
    image.save(image_path)
    print(f"Image saved at {image_path}")

# Ask the user for a prompt
user_prompt = input("Enter your prompt for image generation: ")

# Call the function with user input
text_to_image(user_prompt)

# Download the image
from google.colab import files
files.download("output_image.png")